apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: basicauths.mittwald.systems
spec:
  group: mittwald.systems
  names:
    kind: BasicAuth
    listKind: BasicAuthList
    plural: basicauths
    singular: basicauth
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}