apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sshkeypairs.mittwald.systems
spec:
  group: mittwald.systems
  names:
    kind: SSHKeyPair
    listKind: SSHKeyPairList
    plural: sshkeypairs
    singular: sshkeypair
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                forceRegenerate:
                  type: boolean
                length:
                  type: string
                encoding:
                  type: string
                  enum: [ "base64", "raw", "base32", "hex", "base64url" ]
                username:
                  type: string
                privateKey:
                  type: string
                data:
                  type: object
                  additionalProperties: true
      subresources:
        status: {}