apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stringsecrets.mittwald.systems
spec:
  group: mittwald.systems
  names:
    kind: StringSecret
    listKind: StringSecretList
    plural: stringsecrets
    singular: stringsecret
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                forceRegenerate:
                  type: boolean
                fieldNames:
                  type: array
                  items:
                    type: string
                length:
                  type: string
                encoding:
                  type: string
                  enum: ["base64", "raw", "base32", "hex", "base64url"]
                data:
                  type: object
                  additionalProperties: true
                fields:
                  type: array
                  items:
                    type: object
                    properties:
                      encoding:
                        type: string
                        enum: ["base64", "raw", "base32", "hex", "base64url"]
                      length:
                        type: string
                      fieldName:
                        type: string
                    required:
                      - fieldName
      subresources:
        status: {}