{{- if .Values.rbac.create -}}
{{- if .Values.useMetricsService -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "mittwald:{{ include "kubernetes-secret-generator.serviceAccountName" . }}"
  labels:
  {{ include "kubernetes-secret-generator.labels" . | nindent 4 }}
rules:
  # leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - "get"
      - "create"
{{ else }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "mittwald:{{ include "kubernetes-secret-generator.serviceAccountName" . }}"
  labels:
  {{ include "kubernetes-secret-generator.labels" . | nindent 4 }}
rules:
  # leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - "get"
      - "create"
{{ end }}
{{- end -}}
